@echo off
REM Este script creará los directorios ASIR, DAM, SMR, DAW Y CETI.
REM Autor: Rocío Alzas Conde.
REM Fecha: 13/11/2023.

mkdir %USERPROFILE%\ASIR\docs %USERPROFILE%\ASIR\pract %USERPROFILE%\ASIR\exam %USERPROFILE%\DAM\docs %USERPROFILE%\DAM\pract %USERPROFILE%\DAM\exam %USERPROFILE%\SMR\docs %USERPROFILE%\SMR\pract %USERPROFILE%\SMR\exam %USERPROFILE%\DAW\docs %USERPROFILE%\DAW\pract %USERPROFILE%\DAW\exam %USERPROFILE%\CETI\docs %USERPROFILE%\CETI\pract %USERPROFILE%\CETI\exam
